
CREATE TABLE IF NOT EXISTS `T_CONTENTS_ID` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB 
  DEFAULT CHARSET=utf8 
  COLLATE=utf8_general_ci
  AUTO_INCREMENT=1000000000
  COMMENT='컨텐츠 ID 생성용 테이블 - C 소스 T_CONTENTS_ID 테이블 대체';
